In [1]:
import numpy as np
X=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
X=X/np.amax(X,axis=0)
y=y/100;

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivatives_sigmoid(x):
    return (1-x)

In [3]:
epoch=1000
learning_rate=0.6
inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1

In [4]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wo=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [5]:
for i in range(epoch):
    net_h=np.dot(X,wh)+bh
    sigma_h=sigmoid(net_h)
    net_o=np.dot(sigma_h,wo)+bo
    output=sigmoid(net_o)
    #backpropagation
    DeltaK=(y-output)*derivatives_sigmoid(output)
    DeltaH=DeltaK.dot(wo.T)*derivatives_sigmoid(sigma_h)
    wo=wo+sigma_h.T.dot(DeltaH)*learning_rate
    wh=wh+X.T.dot(DeltaH)*learning_rate

In [6]:
print(f"Input: \n {X}")
print(f"Actual Output: \n {y}")
print(f"Predicted Output: \n {output}")

Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.85087044 0.8852169  0.96526757]
 [0.82988471 0.86381805 0.95093086]
 [0.85031075 0.88457021 0.9647784 ]]
